services:
  edumatch-db:
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}

  edumatch-redis:
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./apps/redis:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
